### ISSUE TITLE
Fantastic repo

### ISSUE THREAD

**Issue by csakis** [charlesread/hmls#3]
Charles!
What a great repo, this is exactly what I need.
I only need to add authentication and database access.
I have a small question, when I edit my css and js files, after a while my static folder is full of lasso buils css and js files. Is there a lasso settings that cleans the directory first, before making new files?

**Comment by charlesread** [comment]
Thanks for the kind words!  Check out my other easy to use plugins for authentication, and the multitude on Hapi's website.  I'm sure that `lasso` provides some cool way to do this, but I don't know what it is, but you could always do it the poor man's way right before you `vc.start()`: 

```js
fs.readdirSync('./static').map(fs.unlinkSync);
```

BE SUPER CAREFUL WITH THAT!  (don't go deleting unintended things)
